### ISSUE TITLE
PKIX path building failed:

### ISSUE THREAD

**Issue by tyrcho** [LeBezout/LEEK-WARS#1]
Salut, merci d'avoir partagé ce projet !

J'ai fait un petit code pour tester et j'ai une exception ... c'est sensé toujours marcher ? Je crois que le certificat du site a changé depuis début janvier. Ou alors j'ai une erreur bête dans mon code ?

```java
package com.leekwars.utils.fastgarden;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.leekwars.utils.DefaultLeekWarsConnector;
import com.leekwars.utils.fastgarden.impl.HtmlReportFastGardenVisitor;

public class Main {
	public static final DefaultLeekWarsConnector tyrcho = new DefaultLeekWarsConnector("tyrcho", "MonPassword");
	private static final File HTML_TEMPLATE_FILE = new File("src/main/resources/report_template.html");
	private static final String TIMESTAMP = new SimpleDateFormat("yyyyMMdd").format(new Date());

	public static void main(String[] args) throws Exception {
		System.setProperty("javax.net.ssl.keyStore", "src/main/security/lw.jks");
		System.setProperty("javax.net.ssl.trustStore", "src/main/security/jssecacerts");

		final File output = new File("target/reports", TIMESTAMP + "_TODO.html");
		HtmlReportFastGardenVisitor lReport = new HtmlReportFastGardenVisitor(HTML_TEMPLATE_FILE, output);
		UltraFastGarden.forAll(tyrcho, lReport);
		lReport.generate();
	}
}
```

```

Exception in thread "main" com.leekwars.utils.exceptions.LWException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.leekwars.utils.http.HttpUtils.get(HttpUtils.java:53)
	at com.leekwars.utils.AbstractLeekWarsConnector.connect(AbstractLeekWarsConnector.java:209)
	at com.leekwars.utils.AbstractLeekWarsConnector.connectIfNeeded(AbstractLeekWarsConnector.java:226)
	at com.leekwars.utils.fastgarden.UltraFastGarden.forAll(UltraFastGarden.java:176)
	at com.leekwars.utils.fastgarden.Main.main(Main.java:24)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1506)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.leekwars.utils.http.HttpUtils.get(HttpUtils.java:49)
	... 4 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1488)
	... 15 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 21 more

**Comment by tyrcho** [comment]
Note : il trouve bien les 2 fichiers. Si je change le path, j'ai une autre erreur :

```
java.io.FileNotFoundException: src\main\lw.jks (The system cannot find the file specified)

**Comment by LeBezout** [comment]
Salut Michel,

merci d'essayer d'utiliser ce petit projet, je me sens moins seul d'un coup
;)

donc oui c'est un pb de certificat. Il change tous les 3 ou 6 mois je sais
plus.

Moi ce que je fais c'est que j'utilise le petit outil "InstallCert"
disponible dans "LEEK-WARS <https://github.com/LeBezout/LEEK-WARS>/
leekwars-utils
<https://github.com/LeBezout/LEEK-WARS/tree/master/leekwars-utils>/src
<https://github.com/LeBezout/LEEK-WARS/tree/master/leekwars-utils/src>/main
<https://github.com/LeBezout/LEEK-WARS/tree/master/leekwars-utils/src/main>/
java
<https://github.com/LeBezout/LEEK-WARS/tree/master/leekwars-utils/src/main/java>
/com
<https://github.com/LeBezout/LEEK-WARS/tree/master/leekwars-utils/src/main/java/com>
/leekwars
<https://github.com/LeBezout/LEEK-WARS/tree/master/leekwars-utils/src/main/java/com/leekwars>
/utils
<https://github.com/LeBezout/LEEK-WARS/tree/master/leekwars-utils/src/main/java/com/leekwars/utils>
/tools
<https://github.com/LeBezout/LEEK-WARS/tree/master/leekwars-utils/src/main/java/com/leekwars/utils/tools>
/InstallCert.java"

Tu lances le main, il va te demander quel certificat importer y'en a qu'un
donc tu tapes 1. Il va te générer le fichier "jssecacerts" c'est celui-la
qu'il va falloir utiliser en "trustStore".

Si ca ne fonctionne tjs pas c'est que ca vient du fichier JKS (le
keyStore). Je ne sais plus trop comment j'avais générer le mien. Tiens moi
au courant. J'essayerai de regarder si besoin.


2017-01-27 0:37 GMT+01:00 Michel Daviot <notifications@github.com>:
